language: minimal

install:
 - curl -qL https://github.com/jedisct1/dnscrypt-proxy/releases/download/2.0.25/dnscrypt-proxy-linux_x86_64-2.0.25.tar.gz | tar xzvf -
 - cd linux-x86_64
 - cp example-dnscrypt-proxy.toml dnscrypt-proxy.toml
 - sed -i -e 's/listen_addresses.*/listen_addresses = ["127.0.0.1:5300"]/' dnscrypt-proxy.toml
 - sed -i -e 's/require_dnssec.*/require_dnssec = false/' dnscrypt-proxy.toml
 - sed -i -e 's/require_nolog.*/require_nolog = false/' dnscrypt-proxy.toml
 - sed -i -e 's/require_nofilter.*/require_nofilter = false/' dnscrypt-proxy.toml

script:
 - ./dnscrypt-proxy -list-all
 - env DEBUG=1 ./dnscrypt-proxy -pidfile /tmp/dnscrypt-proxy.pid -loglevel 0 &
 - sleep 60
 - kill $(cat /tmp/dnscrypt-proxy.pid)
